apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-api
  namespace: my-cicd
  labels:
    app: ops-api
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: ops-api
  template:
    metadata:
      labels:
        app: ops-api
    spec:
      serviceAccountName: endpoints-finder
      containers:
      - name: ops-api
        image: jiangbo2018/ops-api:v1.0.1
        ports:
        - containerPort: 8888
        readinessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: ops-api-svc
  namespace: my-cicd
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    name: api
    protocol: TCP
  selector:
    app: ops-api

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ops-api-hpa-c
  namespace: my-cicd
  labels:
    app: ops-api-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ops-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ops-api-hpa-m
  namespace: my-cicd
  labels:
    app: ops-api-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ops-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
